formats:
  rose-title: "&b<name>&c's heart."
  point-boost-message: "&7Point Boost! &6<perc>&7 percent boost!"
  double-vote: "&6Your vote has been counted &a2x"
  priority-join: "&6You have joined using your priority join!"
  snowballs-delivered: "&3You have been given &a256&3 more snowballs."
  must-be-hub: "&cYou can only use /shop on the hub!"
  gui:
    shop-title: "&aShop: Item Shop"
    tier-title: "&aShop: Tier Shop"
    tier-lore: "&6Tier: <tier>"
    points-price-lore: "&aPoints: &6<points>"
    donor-price-lore: "&aCactus Points: &6<points>"
    already-purchased-lore: "&aYou already have this item!"
    cannot-purchase: "&cYou cannot purchase this item yet!"
    cannot-purchase-reason: "&cYou cannot purchase this item: <reason>"
    click-to-purchase-lore: "&aClick to purchase!"
    already-have-tier-lore: "&aYou have unlocked this teir!"
    tier-price-lore: "&aPoints: &6<points>"
    tier-can-purchase-lore: "&aYou can unlock this tier with points!"
    required-level-lore: "&cThis requires level &a<level>&c."
    tier-shop-title: "&bView/Purchase &cTiers"
    item-shop-title: "&bView/Purchase &6Items"
    info-title: "&3About the TBNR Shop:"
    purchase-error: "&cFailed to purchase item: <reason>"
    help-text:
    - "&bYou can purchase most items in the TBNR Shop"
    - "&busing donor credits, which you can purchase"
    - "&bon our website at tbnr.net, or using points"
    - "&b(for most items) which you earn ingame during"
    - "&bplaytime. Items have specific tiers, some of"
    - "&bwhich, you must unlock using ingame points and"
    - "&blevels. These tiers dictate price, and purchase"
    - "&boptions. &c&lIN ALL TRANSACTIONS, IF YOU HAVE"
    - "&c&lDONOR POINTS (CACTUS POINTS), THEY WILL BE USED IF POSSIBLE."
