formats:
  rose-title: "&b<name>&c's heart."
  point-boost-message: "&7Point Boost! &6<perc>&7 percent boost!"
  double-vote: "&6Your vote has been counted &a2x"
  priority-join: "&6You have joined using your priority join!"
  snowballs-delivered: "&3You have been given &a256&3 more snowballs."
  gui:
    shop-title: "&aShop: Item Shop"
    tier-title: "&aShop: Tier Shop"
    tier-lore: "&6Tier: <tier>"
    points-price-lore: "&aPoints: &6<points>"
    donor-price-lore: "&aCactus Points: &6<points>"
    already-purchased-lore: "&aYou already have this item!"
    cannot-purchase: "&cYou cannot purchase this item yet!"
    cannot-purchase-reason: "&cYou cannot purchase this item: <reason>"
    click-to-purchase-lore: "&aClick to purchase!"
    already-have-tier-lore: "&aYou have unlocked this teir!"
    tier-price-lore: "&aPoints: &6<points>"
    tier-can-purchase-lore: "&aYou can unlock this tier with points!"
    required-level-lore: "&cThis requires level &a<level>&c."
