formats:
  class-pass-item-name: "&aClasses"
  class-chosen: "&aYou have chosen class: &c<class-name>"
  class-no-credits: "&cYou have no credits for this class"
  stats: "&3To see detailed stats click this link &a<url>"
  stats-url: "stats.tbnr.net/<player>"
  no-youtube: "&cThat player does not have a Youtube channel."
  failed-youtube: "&cFailed to retrieve Youtube channel data."
  youtube-display: "&3<key> &5: &b<value>"
  set-youtube-this: "&3Setting your Youtube username to the following data:"
  fail-set: "&cFailed to find your Youtube channel!"