formats:
  class-pass-item-name: "&aClasses"
  class-chosen: "&aYou have chosen class: &c<class-name>"
  class-no-credits: "&cYou have no credits for this class"
  stats: "&3To see detailed stats click this link &a<url>"
  stats-url: "stats.tbnr.net/<player>"
  no-youtube: "&cThat player does not have a Youtube channel."
  failed-youtube: "&cFailed to retrieve Youtube channel data."
  youtube-display: "&3<key> &5: &b<value>"
  set-youtube-this: "&3Setting your Youtube username to the following data:"
  fail-set: "&cFailed to find your Youtube channel!"
  prefix: "&7[&6TBNR&7]"
  xp-change: "&aYou have &c<action> <xp> XP to/from <target>&a."
  xp-changed: "&aYou've had &c<xp> XP <action>&a."
  points-sidebar: "&bPoints:"
  sidebar-title: "&eTBNR Stats:"
  sidebar-title-loading: "&8Loading..."
  xp-sidebar: "&bXP:"
  level-sidebar: "&bLevel:"
  donor-points-sidebar: "&aCactusPoints:"
  xp-earned: "<p>You have earned <s><xp><p> XP for playing!"
  points-earned: "<p>You have earned <s><points><p> points for playing!"
  points-added: "<p>You have earned <s><points><p> points!"
  game-void: "&cYour points and XP from this game will not be earned."
  level-up: "&aYou have leveled up to level &c<level>&a."
