name: TBNRNetwork
authors: [Twister915]
version: 1.2
description: Manages TBNR specifics for Gearz
main: net.tbnr.manager.TBNRNetworkManager
depend: [Gearz]
commands:
    xp:
      description: Xp
    clearchat:
      description: Clears chat
      aliases: [cc, cchat, clearc]
    clearmychat:
      description: Clears senders chat
      aliases: [cmc, cmychat]
