formats:
  diamond-title: "<p>Right click this to bank your skulls."
  winner: "<p><player><s> has won <p>Plague<s>."
  time-remaining: "<p>Time remaining in the game: <s><timespec>"
  waste-bone-meal: "<p>Don't waste your bonemeal on none <s>infected <p>people"
  cured-zombie: "<p>You have cured <player>, well done!"
  turned-zombie: "<p>You are now a zombie, go kill the <s>humans!"
  cure-poison: "<p>You have cured your poison!"
  make-human: "<p>You are now human, go defend yourself against the <s>Zombies<p>!"
  waste-milk: "<p>Don't waste your milk on none <s>poisoned <p>people"
  poison-cure: "<p>Right Click To Cure Yourself Of Poison Or Another Person!"
  zombie-cure: "<p>Right Click To Cure Another Person (Make them become Human)!"
  cured-poison-other: "<p>You have cured <player> of poison, well done!"
  scoreboard-title: "<p>Points<s>!"