formats:
  diamond-title: "<p>Right click this to bank your skulls."
  scoreboard-title: "<s>Scores:"
  winner: "<p><player><s> has won <p>Head Hunter<s>."
  time-remaining: "<p>Time remaining in the game: <s><timespec>"